// setConfig types
export enum UserApplicationConfigType {
    CONFIG_TYPE_INBOUND_PROOF_LIBRARY_VERSION = 1,
    CONFIG_TYPE_INBOUND_BLOCK_CONFIRMATIONS,
    CONFIG_TYPE_RELAYER,
    CONFIG_TYPE_OUTBOUND_PROOF_TYPE,
    CONFIG_TYPE_OUTBOUND_BLOCK_CONFIRMATIONS,
    CONFIG_TYPE_ORACLE
}
